version: '3'

vars:
  GIT_TAG:
    sh: git describe --tags HEAD 2>/dev/null || echo v0.0.0
  GIT_COMMIT:
    sh: git rev-parse --short HEAD || echo unknown
  LDFLAGS: >-
    -X github.com/abdusco/imgz/internal/version.CommitHash={{.GIT_COMMIT}}
    -X github.com/abdusco/imgz/internal/version.Version={{.GIT_TAG}}
    -X github.com/abdusco/imgz/internal/version.BuildDate={{dateInZone "2006-01-02T15:04:05Z07:00" (now) "UTC"}}

tasks:
  build:
    cmds:
      - go build -v -ldflags "{{.LDFLAGS}}" github.com/abdusco/imgz/cmd/imgz
  deploy:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -v -ldflags "{{.LDFLAGS}}" -o ./out/imgz ./cmd/imgz/
      - rsync -rvPa ./out/imgz $REMOTE_SERVER:~/.bin/